services:
  jira:
    depends_on:
      - db
    build:
      context: ./
      args:
        JIRA_VERSION: ${JIRA_VERSION}
    container_name: jirasoftware
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@db/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'CATALINA_OPTS= -Xms256m -Xmx4g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
      - 'JIRA_DB_HOST=db'
      - 'JIRA_DB_PORT=5432'

  db:
    image: postgres:15.8
    hostname: postgresql
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
