services:
  jira:
    image: ghcr.io/eugenmayer/jira:${JIRA_VERSION}
    depends_on:
      - db
    container_name: jira
    volumes:
      - jiradata:/var/atlassian/jira
      - ./jira-opt/lib/atlassian-extras-3.4.6.jar:/opt/jira/atlassian-jira/WEB-INF/lib/atlassian-extras-3.4.6.jar:ro
      - ./jira-opt/lib/atlassian-extras-key-manager-3.4.6.jar:/opt/jira/atlassian-jira/WEB-INF/lib/atlassian-extras-key-manager-3.4.6.jar:ro
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@db/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'JIRA_DB_HOST=db'
      - 'JIRA_DB_PORT=5432'
      - 'CATALINA_OPTS= -Xms256m -Xmx4g'
      - "JVM_SUPPORT_RECOMMENDED_ARGS=-Dupm.plugin.upload.enabled=true"
      - "JIRA_PROXY_NAME="
      - "JIRA_PROXY_PORT="
      - "JIRA_PROXY_SCHEME="
      - "JIRA_PROXY_SECURE="

  db:
    image: postgres:15.8
    hostname: postgresql
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false